/* eslint-disable react-hooks/exhaustive-deps */
// --- React Methods
import React, { useContext, useEffect, useMemo } from "react";
import { useRouter } from "next/router";
import Link from "next/link";

// --Components
import PageRoot from "../components/PageRoot";
import { CardList } from "../components/CardList";
import { JsonOutputModal } from "../components/JsonOutputModal";
import { Footer } from "../components/Footer";
import Header from "../components/Header";
import BodyWrapper from "../components/BodyWrapper";
import PageWidthGrid from "../components/PageWidthGrid";
import HeaderContentFooterGrid from "../components/HeaderContentFooterGrid";
import { DoneToastContent } from "../components/DoneToastContent";
import { DashboardScorePanel } from "../components/DashboardScorePanel";
import { DashboardValidStampsPanel } from "../components/DashboardValidStampsPanel";
import { ExpiredStampsPanel } from "../components/ExpiredStampsPanel";

// --Chakra UI Elements
import {
  Modal,
  ModalBody,
  ModalContent,
  ModalFooter,
  ModalOverlay,
  Spinner,
  useDisclosure,
  useToast,
} from "@chakra-ui/react";



export default function LeaderBoard() {


  return (
    <PageRoot className="text-color-1">
      <HeaderContentFooterGrid>
        <Header />
        <BodyWrapper className="mt-4 md:mt-6">
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE 

          {/* <PageWidthGrid>
            <Subheader className="col-span-full xl:col-span-7 " />
            <DashboardScorePanel
              className={`col-span-full ${useCustomDashboardPanel ? "lg:col-span-4" : "xl:max-h-52"} xl:col-span-7`}
            />
            {useCustomDashboardPanel || (
              <DashboardIllustration className="col-start-8 col-end-[-1] row-span-2 hidden xl:block" />
            )}
            {useCustomDashboardPanel && (
              <DynamicCustomDashboardPanel
                customizationKey={customizationKey}
                className="col-start-1 col-end-[-1] lg:col-start-5 xl:col-start-8"
              />
            )}
            <span className="col-start-1 col-end-4 font-heading text-4xl">Add Stamps</span>
            <CardList
              className="col-span-full"
              isLoading={
                isLoadingPassport == IsLoadingPassportState.Loading ||
                isLoadingPassport == IsLoadingPassportState.CreatingPassport ||
                isLoadingPassport == IsLoadingPassportState.FailedToConnect
              }
            />
            <span className="col-start-1 col-end-4 font-heading text-3xl">Add Collected Stamps</span>
            <span className="col-end-[-1] self-center whitespace-nowrap text-right font-alt text-3xl text-foreground-2">
              {numVerifiedPlatforms}/{numPlatforms}
            </span>
            <DashboardValidStampsPanel className="col-span-full" />
            <ExpiredStampsPanel className="col-span-full" />
          </PageWidthGrid> */}
        </BodyWrapper>
        {/* This footer contains dark colored text and dark images */}
        <Footer lightMode={true} />
      </HeaderContentFooterGrid>
    </PageRoot>
  );
}
