/* eslint-disable react-hooks/exhaustive-deps */
// --- React Methods
import React, { useContext, useEffect, useMemo } from "react";
import { useRouter } from "next/router";
import Link from "next/link";

// --Components
import PageRoot from "../components/PageRoot";
import { CardList } from "../components/CardList";
import { JsonOutputModal } from "../components/JsonOutputModal";
import { Footer } from "../components/Footer";
import Header from "../components/Header";
import BodyWrapper from "../components/BodyWrapper";
import PageWidthGrid from "../components/PageWidthGrid";
import HeaderContentFooterGrid from "../components/HeaderContentFooterGrid";
import { DoneToastContent } from "../components/DoneToastContent";
import { DashboardScorePanel } from "../components/DashboardScorePanel";
import { DashboardValidStampsPanel } from "../components/DashboardValidStampsPanel";
import { ExpiredStampsPanel } from "../components/ExpiredStampsPanel";

// --Chakra UI Elements
import {
  Modal,
  ModalBody,
  ModalContent,
  ModalFooter,
  ModalOverlay,
  Spinner,
  useDisclosure,
  useToast,
} from "@chakra-ui/react";

export default function LeaderBoard() {
  return (
    <PageRoot className="text-color-1">
      <HeaderContentFooterGrid>
        <Header />
        <BodyWrapper className="mt-4 md:mt-6">
          BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF
          THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE
          LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD
          PAGE BODY OF THE LEADERBOARD PAGE BODY OF THE LEADERBOARD PAGE
        </BodyWrapper>
      </HeaderContentFooterGrid>
    </PageRoot>
  );
}
