name: Library - Deploy Infra only - Generic
on:
  workflow_call:
    inputs:
      refspec:
        description: "The commit SHA"
        type: string
        required: True
      environment:
        description: "Environment to deploy to"
        type: string
        required: true

jobs:
  deploy_preview:
    name: Preview - Deploying AWS Infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.refspec }}
          fetch-depth: 0
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          AWS_ACCESS_KEY_ID: op://DeployerVault/github-aws-${{ inputs.environment }}/ci/AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: op://DeployerVault/github-aws-${{ inputs.environment }}/ci/AWS_SECRET_ACCESS_KEY
          PULUMI_ACCESS_TOKEN: op://DeployerVault/github-aws-${{ inputs.environment }}/ci/PULUMI_ACCESS_TOKEN
          CLOUDFLARE_API_TOKEN: op://DeployerVault/github-aws-${{ inputs.environment }}/ci/CLOUDFLARE_API_TOKEN
          
      - name: Set AWS_SESSION_TOKEN if needed
        if: inputs.environment == 'production'
        run: echo "AWS_SESSION_TOKEN=$(op read op://DeployerVault/github-aws-production/ci/AWS_SESSION_TOKEN)" >> $GITHUB_ENV

      - name: Prepare to Deploy to AWS
        uses: passportxyz/gh-workflows/.github/actions/prepare_deploy_to_aws@v1
      - name: Preview Deploy
        uses: passportxyz/gh-workflows/.github/actions/deploy_to_aws@v1
        with:
          docker_tag: ${{ inputs.refspec }}
          stack_name: passportxyz/id-staking-v2/${{ inputs.environment }}
          aws_region: us-west-2
          pulumi_command: preview
          pulumi_diff: true
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ env.PULUMI_ACCESS_TOKEN }}
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ env.CLOUDFLARE_API_TOKEN }}

  deploy_confirm:
    name: Review Approval Pending
    needs: [deploy_preview]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Approve Release to Review (check pulumi preview)
        run: |
          echo "Ref" ${{ inputs.refspec }}

  deploy_backends:
    name: Deploying AWS Infra
    needs: [deploy_preview, deploy_confirm]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.refspec }}
          fetch-depth: 0
      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          AWS_ACCESS_KEY_ID: op://DeployerVault/github-aws-${{ inputs.environment }}/ci/AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: op://DeployerVault/github-aws-${{ inputs.environment }}/ci/AWS_SECRET_ACCESS_KEY
          PULUMI_ACCESS_TOKEN: op://DeployerVault/github-aws-${{ inputs.environment }}/ci/PULUMI_ACCESS_TOKEN
          CLOUDFLARE_API_TOKEN: op://DeployerVault/github-aws-${{ inputs.environment }}/ci/CLOUDFLARE_API_TOKEN

      - name: Set AWS_SESSION_TOKEN if needed
        if: inputs.environment == 'production'
        run: echo "AWS_SESSION_TOKEN=$(op read op://DeployerVault/github-aws-production/ci/AWS_SESSION_TOKEN)" >> $GITHUB_ENV
      
      - name: Prepare to Deploy to AWS
        uses: passportxyz/gh-workflows/.github/actions/prepare_deploy_to_aws@v1

      - name: Deploy to AWS
        uses: passportxyz/gh-workflows/.github/actions/deploy_to_aws@v1
        with:
          docker_tag: ${{ inputs.refspec }}
          stack_name: passportxyz/id-staking-v2/${{ inputs.environment }}
          aws_region: us-west-2
          pulumi_command: up
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ env.PULUMI_ACCESS_TOKEN }}
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          CLOUDFLARE_API_TOKEN: ${{ env.CLOUDFLARE_API_TOKEN }}
